import calendar from '../images/dashboard/calendar-tp.png'
import venue from '../images/dashboard/venue-dash-card.jpg'
import catering from '../images/dashboard/catering-dash-card.jpg'
import photography from '../images/dashboard/photography-dash-card.jpg'
import pans from '../images/dashboard/pans.png'
import soundbar from '../images/dashboard/soundbar.png'
import towels from '../images/dashboard/towels.png'
import celebration from '../images/dashboard/celebration-will-smith.gif'
import clipboard from '../images/dashboard/guests-clipboard-tp.png'
import location from '../images/dashboard/3d-location-tp.png'
import clock from '../images/dashboard/clock-tp.png'
import dancing from '../images/dashboard/funny-dancing.gif'
import pillows from '../images/dashboard/pillows.jpg'
import bedroomessentials from '../images/dashboard/pillows-tp.png'
import box from '../images/dashboard/box-tp.png'
import washingmachine from '../images/dashboard/washing-machine-tp.png'
import drinkware from '../images/dashboard/drinkware-tp.png'
import tchotchke from '../images/dashboard/tchotchke-tp.png'
import kitchenappliances from '../images/dashboard/kitchen-appliances-tp.png'
import diningessentials from '../images/dashboard/dining-essentials-tp.png'
import kitchenware from '../images/dashboard/kitchenware.jpg'
import homedecor from '../images/dashboard/home-decor.png'
import weddingservices from '../images/others/wed-services-tp.png'
import planningadvice from '../images/others/planning-tp.png'
import weddingceremony from '../images/others/wedding-ceremony-tp.png'
import weddingfashion from '../images/others/wedding-fashion.png'
import destinationweddings from '../images/others/destination-tp.png'


export default {destinationweddings, weddingfashion, weddingceremony, weddingservices, planningadvice, kitchenware, bedroomessentials, diningessentials, homedecor, kitchenappliances, tchotchke, drinkware, washingmachine, box, calendar, venue, catering, photography, pans, soundbar, towels, celebration, clipboard, location, clock, dancing, pillows}